version: '3.8'

services:
    api:
        image: rsds/api
        container_name: rsds_api
        networks:
            - api_net
        ports:
            - 3333:3333

    frontend:
        image: rsds/frontend
        container_name: rsds_frontend
        ports:
            - 4201:80

networks:
    api_net:
        driver: bridge
