name: Lint & Test PR

on:
    pull_request:
        branches: [develop]

    workflow_dispatch:

jobs:
    lint-test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - run: git fetch origin $NX_BRANCH

            - uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Install dependencies
              run: npm ci

            - name: Run Lint & Tests
              uses: mansagroup/nrwl-nx-action@v3
              with:
                  targets: lint,test
                  affected: 'true'
